name: Check Latest Release

on:
  push:
    branches:
      - main

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check latest release version
        id: latest_release
        run: echo "::set-output name=release::$(curl --silent 'https://api.github.com/repos/:owner/:repo/releases/latest' | jq -r '.tag_name')"
      - name: Display latest release version
        run: echo "Latest release version is ${{ steps.latest_release.outputs.release }}"
