name: Check Latest Release

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      VARIABLE_NAME: value
    steps:
      - name: My step
        run: echo "LATEST_RELEASE=${VARIABLE_NAME}" >> $GITHUB_ENV

      - name: My step
        run: echo env.PREVIOUS_RELEASE
