name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest version
        id: latest_version9
        run: |
          latest_version=$(curl --silent "https://api.github.com/repos/langhuihui/monibuca/releases/latest" | jq -r .tag_name | sed 's/^v//')
          echo "::set-output name=latest_version::$latest_version"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: chm852098505/m7s:${{ steps.latest_version.outputs.latest_version }}
          dockerfile: ./Dockerfile
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
