name: Check Latest Release

on:
  push:
    branches:
      - main

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:

      - name: show
        run: echo "${{ env.MY_VARIABLE }}"

      - name: Store variable
        run: echo "MY_VARIABLE=hello" >> $GITHUB_ENV
      - name: Save variable to repo secrets
        uses: montudor/action-set-repo-secret@v1.1
        with:
          name: MY_VARIABLE
          value: ${{ env.MY_VARIABLE }}