name: Check Latest Release

on:
  push:
    branches:
      - main

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      -
      - name: Save variable to environment
        run: echo "MY_VARIABLE=my_value" >> $GITHUB_ENV

      - name: Save to Repository Environment
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Save MY_VARIABLE to Repository Environment'
          file_pattern: 'README.md'
          name: 'Save MY_VARIABLE'
          email: '852098505@qq.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_VARIABLE: ${{ env.MY_VARIABLE }}
