name: Check Latest Release

on:
  push:
    branches:
      - main

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.MY_VARIABLE }}"
      - name: Save variable to environment
        run: echo "MY_VARIABLE=my_value" >> $GITHUB_ENV
