name: Check Latest Release

on:
  push:
    branches:
      - main

jobs:
  download-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release
        run: |
          latest_release=$(curl --silent 'https://api.github.com/repos/langhuihui/monibuca/releases/latest' | jq -r '.tag_name')
          echo "LATEST_RELEASE=${latest_release}" >> $GITHUB_ENV
